wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683236213.161772
    t:
      1:
      - 1
      - 5
      - 41
      - 43
      - 49
      - 50
      - 53
      - 55
      - 63
      - 77
      2:
      - 1
      - 5
      - 41
      - 43
      - 49
      - 50
      - 53
      - 55
      - 63
      - 77
      3:
      - 13
      - 19
      - 23
      4: 3.9.16
      5: 0.15.1
      8:
      - 5
query_radius:
  desc: null
  value: 0.16
pos_wt:
  desc: null
  value: 1.0
ori_wt:
  desc: null
  value: 0.01
gripper_wt:
  desc: null
  value: 0.001
