"handover-to-person":
  - "approach-person"
  - "align-with-hand"
  - "release-object"

"open-object-drawer":
  - "align-with-handle"
  - "grasp-handle"
  - "pull-out-handle"

"close-object-drawer":
  - "align-with-surface"
  - "close-gripper"
  - "push-in"

"pour-into-bowl":
  - "align-with-bowl"
  - "tilt-into-bowl"
  - "tilt-further"
  - "empty-out"

"take-bottle":
  - "align-with-bottle"
  - "grasp-bottle"
  - "lift-bottle"
  - "retract-arm"

