validate: False
datadir: "/home/priparashar/h5_test/stretch_testing/pick_up_bottle/03-22/"
template: "*.h5"
load: False
resume: False
debug: False
learning_rate: 1e-3
task_name: over_fit_pick_up_bottle_fixed
source: robopen
run_for: -1
wandb: False
split: False
data_augmentation: False
color_jitter: False
loss_fn: "xent"

