# Encoder setup
encoder: "clip"
encoder_args: "ViT-B/32"

# Sparse Voxel Map parameters
voxel_size: 0.02
obs_min_height: 0.1
obs_max_height: 1.8
obs_min_density: 10  # This many points makes it an obstacle
pad_obstacles: 1  # Add this many units (voxel_size) to the area around obstacles
local_radius: 0.8  # Area around the robot to mark as explored (kind of a hack)
smooth_kernel_size: 2 
pad_obstacles: 0
min_depth: 0.1
max_depth: 4.0

# Navigation space
step_size: 0.1  # (originally .1, we can make it all the way to 2 maybe actually)
rotation_step_size: 0.2
dilate_frontier_size: 12
dilate_obstacle_size: 5

# Trajectory following
trajectory_pos_err_threshold: 0.15
trajectory_rot_err_threshold: 0.3
trajectory_per_step_timeout: 3.0
 
